### ISSUE TITLE
翻訳機能処理の動作確認

### ISSUE THREAD

**Issue by t-nakatani** [t-nakatani/CI_teamC#14]
## やってほしいこと
* 各処理でどれくらい時間がかかるか調査
  * `model = EasyNMT('opus-mt')`
  * `model.translate(text)`
* 処理に必要なモデル(パラメータ)をmodel.translate()の前にloadするコードの作成
***
作業環境
* [feature/confirm_translation](https://github.com/t-nakatani/CI_teamC/tree/feature/confirm_translation)
* notebookは[confirm_translation.ipynb](https://github.com/t-nakatani/CI_teamC/blob/feature/confirm_translation/confirm_translation.ipynb)使ってもらっても別のやつ使ってもらってもOKです！

1. ビルド
```sh
docker-compose build
```
2. 起動
```sh
docker-compose up 
```

3. アクセス
[localhost:9090](http://localhost:9090/lab)にアクセス

**Comment by tsujiwaki** [comment]
それぞれの処理でどのくらい時間がかかっているかを調査しました。
わざわざ.ipynb作ってくれたのになぜかエラーで上手く実行できなかったので、
Google Colabで調査することにしました。ごめんなさい。

`model = EasyNMT('opus-mt')`と、`get_translate(model, text)`を5回でやってみました。

![スクリーンショット (1805)](https://user-images.githubusercontent.com/118955121/212858195-981c3e7d-2fb6-4d46-8239-b0ef6b218356.png)

`model = EasyNMT('opus-mt')`はほぼ無視できるくらいの時間でした。
5回の`get_translate(model, text)`は、1回目が少し長く、2回目以降は短かったです。
また、翻訳したい文の長さにおよそ比例して実行時間も長くなるようです。

これをみると、`model = EasyNMT('opus-mt')`の段階では処理に必要なモデル（パラメータ）をロードしておらず、1回目の`get_translate(model, text)`で3秒強かけてロードしているのかなと思います。

そこで、`get_translate(model, text)`の前に処理に必要なモデルをロードする方法を調べていたのですが、方法がわからず、難しかったです。。。ごめんなさい。
色々見ても`model = EasyNMT('opus-mt')`でモデルの読み込みをするような書き方になってるように思いました。
なにか別の方法があるんかな。
- https://github.com/UKPLab/EasyNMT/blob/main/easynmt/EasyNMT.py
- https://www.hamlet-engineer.com/posts/pdf_translate_02.html

また、動作確認をしようとしたのですが、もともとのDockerのメモリ2MBではKilledになってexit code: 137で強制終了になったので、メモリを8MBにしました。
その後にdocker-compose buildを実行して約20分ほどで完了し、
次にdocker-compose upを実行したのですが途中でおそらく容量不足に、、、
さらに容量回復のためにDISKPARTでWSLを圧縮とかしているうちにWSLが壊れちゃいました😂

なので、どなたか処理に必要なモデルを先に読み込む方法と、翻訳機能の動作確認とをお願いできますか、、、役に立てず申し訳ないです。

![スクリーンショット (1802)](https://user-images.githubusercontent.com/118955121/212864065-9721a289-285e-4092-9b8c-1d65fd63ac5b.png)
↑ docker-compose buildにはかなり時間がかかります

**Comment by tsujiwaki** [comment]
調査で使った日本語は、
- APIの勉強のために, Twitter apiを用いてユーザのツイート取得を行ったので, 簡単に流れをまとめました.以下が内容です.1. Twitter developerでのAPI申請2. APIを用いてのツイート取得をcurlコマンドで行う
- 今日は良い天気ですね

です。

**Comment by tsujiwaki** [comment]
Twitterは140文字の制限があって、翻訳するツイートの量を4つに制限すれば、
翻訳自体にはそこまで時間はかからないのかなと思いました。

**Comment by t-nakatani** [comment]
@tsujiwaki 
めちゃくちゃ大変やったろうにありがとう！
調べてくれた内容使って完成させれると思う:+1:

**Comment by tsujiwaki** [comment]
こちらこそありがとう、動作確認までうまいことできんくてごめんなさい！あのあとWSLは治ったけど容量が足りなさすぎる、、、さっきHDD買ったけど届くの19日やからそれまで動作確認できひんわ😂
HDD届いたらアプリ実行させて、デモ動画も撮ろうと思います！

**Comment by t-nakatani** [comment]
>model = EasyNMT('opus-mt')はほぼ無視できるくらいの時間でした。
5回のget_translate(model, text)は、1回目が少し長く、2回目以降は短かったです。

この情報めっちゃ助かった！一回目の翻訳load処理用として事前に済ませておくことにした．

```py
trans_model = EasyNMT('opus-mt')
trans_model.translate('これはサンプルテキストです', target_lang='en', max_new_tokens=500)  # for load model
```

妥協解にはなるけど解決したのでcloseします！
