### ISSUE TITLE
埋め込みツイートが取得できない

### ISSUE THREAD

**Issue by t-nakatani** [t-nakatani/CI_teamC#7]
## 概要
ツイートのURLは2種類あるらしく，自分達が取得しているURLでは埋め込みツイートが取得できない
* `https://twitter.com/<USR_ID>/status/<TWEET_ID>` 
* `https://twitter.com/i/web/status/<TWEET_ID>` (こちらを取得)

## 解決策
* twitter APIのグレードをElevatedに上げる
* 埋め込み以外の方法で表示

**Comment by t-nakatani** [comment]
@yusuke-higo 
>twitter APIのグレードをElevatedに上げる

グレード上げるのどれくらい大変そう？
https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api

**Comment by yusuke-higo** [comment]
調べる文にはそんなに難しくなさそうなのでとりあえずやってみます

**Comment by t-nakatani** [comment]
ありがとう:sob:

**Comment by yusuke-higo** [comment]
elevatedになっていると思うので試してみてください

**Comment by t-nakatani** [comment]
助かる！！
API_KEYとかは変わったりしてない？

**Comment by yusuke-higo** [comment]
多分変わってないと思うよ〜

**Comment by t-nakatani** [comment]
できたわ〜ありがと！
